version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore SampleMomusPipelineDemo/SampleMomusPipelineDemo.csproj
  build:
    commands:
      - dotnet build SampleMomusPipelineDemo/SampleMomusPipelineDemo.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ SampleMomusPipelineDemo/SampleMomusPipelineDemo.csproj
artifacts:
  files:
    - '**/*'